package co.edu.udec.poo.gabrielaorozco.examenesacademicos.vistas.gui;

import co.edu.udec.poo.gabrielaorozco.examenesacademicos.modelo.controlador.AlumnoController;
import co.edu.udec.poo.gabrielaorozco.examenesacademicos.modelo.controlador.CursoController;
import co.edu.udec.poo.gabrielaorozco.examenesacademicos.modelo.controlador.DepartamentoAcademicoController;
import co.edu.udec.poo.gabrielaorozco.examenesacademicos.modelo.controlador.ProfesorController;
import co.edu.udec.poo.gabrielaorozco.examenesacademicos.modelo.entidades.Alumno;
import co.edu.udec.poo.gabrielaorozco.examenesacademicos.servicios.AlumnoServicio;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private AlumnoController alumnoController;
    private CursoController cursoController;
    private ProfesorController profesorController;
    private DepartamentoAcademicoController departamentoAcademicoController;

    /**
     * Constructor con dependencia opcional
     */
    public VentanaPrincipal(AlumnoController alumnoController
            , CursoController cursoController, ProfesorController profesorController, DepartamentoAcademicoController departamentoAcademicoController) {
        this.alumnoController = alumnoController;
        this.cursoController = cursoController;
        this.profesorController = profesorController;
        this.departamentoAcademicoController = departamentoAcademicoController;
        initComponents();
        // Aquí puedes usar alumnoServicio si lo necesitas
    }

    /**
     * Constructor sin argumentos (por compatibilidad o pruebas)
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        barraMenu = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        itemGestionarAlumno = new javax.swing.JMenuItem();
        itemListarAlumnos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuProfesores = new javax.swing.JMenu();
        itemGestionarProfesor = new javax.swing.JMenuItem();
        itemListarProfesores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuAsignaturas = new javax.swing.JMenu();
        itemGestionarAsignatura = new javax.swing.JMenuItem();
        itemListarAsignaturas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuCursos = new javax.swing.JMenu();
        itemGestionarCurso = new javax.swing.JMenuItem();
        itemListarCursos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuDepAcademiccos = new javax.swing.JMenu();
        itemGestionarDepAcademico = new javax.swing.JMenuItem();
        itemListarDepsAcademicos = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuExamenes = new javax.swing.JMenu();
        itemGestionarExamen = new javax.swing.JMenuItem();
        itemListarExamenes = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuPracticas = new javax.swing.JMenu();
        itemGestionarPractica = new javax.swing.JMenuItem();
        itemListarPracticas = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuTemas = new javax.swing.JMenu();
        itemGestionarTema = new javax.swing.JMenuItem();
        itemListarTemas = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuAyuda = new javax.swing.JMenu();
        itemMenuAyuda = new javax.swing.JMenuItem();

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..::Universidad de Chile::..");
        setName(""); // NOI18N

        barraMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/alumno32px.png"))); // NOI18N
        menuAlumnos.setText("Alumnos");
        menuAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarAlumno.setText("Gestionar Alumno...");
        itemGestionarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarAlumnoActionPerformed(evt);
            }
        });
        menuAlumnos.add(itemGestionarAlumno);

        itemListarAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarAlumnos.setText("Listar Alumnos...");
        itemListarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(itemListarAlumnos);
        menuAlumnos.add(jSeparator1);

        barraMenu.add(menuAlumnos);

        menuProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/profesor32px.png"))); // NOI18N
        menuProfesores.setText("Profesores");
        menuProfesores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarProfesor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarProfesor.setText("Gestionar Profesor...");
        itemGestionarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarProfesorActionPerformed(evt);
            }
        });
        menuProfesores.add(itemGestionarProfesor);

        itemListarProfesores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarProfesores.setText("Listar Profesores...");
        itemListarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarProfesoresActionPerformed(evt);
            }
        });
        menuProfesores.add(itemListarProfesores);
        menuProfesores.add(jSeparator2);

        barraMenu.add(menuProfesores);

        menuAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/asignaturas32px.png"))); // NOI18N
        menuAsignaturas.setText("Asignaturas");
        menuAsignaturas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarAsignatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarAsignatura.setText("GestionarAsignatura...");
        itemGestionarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarAsignaturaActionPerformed(evt);
            }
        });
        menuAsignaturas.add(itemGestionarAsignatura);

        itemListarAsignaturas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarAsignaturas.setText("Listar Asignaturas...");
        itemListarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarAsignaturasActionPerformed(evt);
            }
        });
        menuAsignaturas.add(itemListarAsignaturas);
        menuAsignaturas.add(jSeparator3);

        barraMenu.add(menuAsignaturas);

        menuCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cursos32px.png"))); // NOI18N
        menuCursos.setText("Cursos");
        menuCursos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarCurso.setText("Gestionar Curso...");
        itemGestionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarCursoActionPerformed(evt);
            }
        });
        menuCursos.add(itemGestionarCurso);

        itemListarCursos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarCursos.setText("Listar Cursos...");
        itemListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCursosActionPerformed(evt);
            }
        });
        menuCursos.add(itemListarCursos);
        menuCursos.add(jSeparator4);

        barraMenu.add(menuCursos);

        menuDepAcademiccos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/depAcad32px.png"))); // NOI18N
        menuDepAcademiccos.setText("Departamento Academico");
        menuDepAcademiccos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarDepAcademico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarDepAcademico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarDepAcademico.setText("Gestionar Dep Academico...");
        itemGestionarDepAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarDepAcademicoActionPerformed(evt);
            }
        });
        menuDepAcademiccos.add(itemGestionarDepAcademico);

        itemListarDepsAcademicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarDepsAcademicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarDepsAcademicos.setText("Listar Deps Academicos");
        itemListarDepsAcademicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarDepsAcademicosActionPerformed(evt);
            }
        });
        menuDepAcademiccos.add(itemListarDepsAcademicos);
        menuDepAcademiccos.add(jSeparator5);

        barraMenu.add(menuDepAcademiccos);

        MenuExamenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/examenes32px.png"))); // NOI18N
        MenuExamenes.setText("Examenes");
        MenuExamenes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarExamen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarExamen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarExamen.setText("GestionarExamen...");
        itemGestionarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarExamenActionPerformed(evt);
            }
        });
        MenuExamenes.add(itemGestionarExamen);

        itemListarExamenes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarExamenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarExamenes.setText("Listar Examenes...");
        itemListarExamenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarExamenesActionPerformed(evt);
            }
        });
        MenuExamenes.add(itemListarExamenes);
        MenuExamenes.add(jSeparator6);

        barraMenu.add(MenuExamenes);

        menuPracticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/practicas32px.png"))); // NOI18N
        menuPracticas.setText("Practicas");
        menuPracticas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarPractica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarPractica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarPractica.setText("Gestionar Practica...");
        itemGestionarPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarPracticaActionPerformed(evt);
            }
        });
        menuPracticas.add(itemGestionarPractica);

        itemListarPracticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarPracticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarPracticas.setText("Listar Practicas...");
        itemListarPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarPracticasActionPerformed(evt);
            }
        });
        menuPracticas.add(itemListarPracticas);
        menuPracticas.add(jSeparator7);

        barraMenu.add(menuPracticas);

        menuTemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/temas32px.png"))); // NOI18N
        menuTemas.setText("Temas");
        menuTemas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGestionarTema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionarTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestionar24px.png"))); // NOI18N
        itemGestionarTema.setText("Gestionar Tema...");
        itemGestionarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarTemaActionPerformed(evt);
            }
        });
        menuTemas.add(itemGestionarTema);

        itemListarTemas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemListarTemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar24px.png"))); // NOI18N
        itemListarTemas.setText("Listar Temas...");
        itemListarTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarTemasActionPerformed(evt);
            }
        });
        menuTemas.add(itemListarTemas);
        menuTemas.add(jSeparator8);

        barraMenu.add(menuTemas);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda32px.png"))); // NOI18N
        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemMenuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda24px.png"))); // NOI18N
        itemMenuAyuda.setText("Acerca de...");
        menuAyuda.add(itemMenuAyuda);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestionarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarAlumnoActionPerformed
        VentanaGestionarAlumno ventana = new VentanaGestionarAlumno(this, true, alumnoController, cursoController);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemGestionarAlumnoActionPerformed

    private void itemGestionarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarProfesorActionPerformed
        VentanaGestionarProfesor ventana = new VentanaGestionarProfesor(this, true, profesorController, departamentoAcademicoController);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemGestionarProfesorActionPerformed

    private void itemGestionarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarAsignaturaActionPerformed

    private void itemListarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarAsignaturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarAsignaturasActionPerformed

    private void itemGestionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarCursoActionPerformed

    private void itemListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarCursosActionPerformed

    private void itemGestionarDepAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarDepAcademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarDepAcademicoActionPerformed

    private void itemListarDepsAcademicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarDepsAcademicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarDepsAcademicosActionPerformed

    private void itemGestionarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarExamenActionPerformed

    private void itemListarExamenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarExamenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarExamenesActionPerformed

    private void itemGestionarPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarPracticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarPracticaActionPerformed

    private void itemListarPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarPracticasActionPerformed

    private void itemGestionarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarTemaActionPerformed

    private void itemListarTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarTemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarTemasActionPerformed

    private void itemListarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarAlumnosActionPerformed
        try {
            List<Alumno> listaAlumnos = alumnoController.getAllAlumnos();

            if (listaAlumnos == null || listaAlumnos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay alumnos registrados", "Resultado negativo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            VentanaListarAlumnos ventana = new VentanaListarAlumnos(this, true, alumnoController, cursoController);
            ventana.setLocationRelativeTo(this);
            ventana.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al intentar abrir la lista de alumnos: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_itemListarAlumnosActionPerformed

    private void itemListarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarProfesoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuExamenes;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemGestionarAlumno;
    private javax.swing.JMenuItem itemGestionarAsignatura;
    private javax.swing.JMenuItem itemGestionarCurso;
    private javax.swing.JMenuItem itemGestionarDepAcademico;
    private javax.swing.JMenuItem itemGestionarExamen;
    private javax.swing.JMenuItem itemGestionarPractica;
    private javax.swing.JMenuItem itemGestionarProfesor;
    private javax.swing.JMenuItem itemGestionarTema;
    private javax.swing.JMenuItem itemListarAlumnos;
    private javax.swing.JMenuItem itemListarAsignaturas;
    private javax.swing.JMenuItem itemListarCursos;
    private javax.swing.JMenuItem itemListarDepsAcademicos;
    private javax.swing.JMenuItem itemListarExamenes;
    private javax.swing.JMenuItem itemListarPracticas;
    private javax.swing.JMenuItem itemListarProfesores;
    private javax.swing.JMenuItem itemListarTemas;
    private javax.swing.JMenuItem itemMenuAyuda;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuAsignaturas;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCursos;
    private javax.swing.JMenu menuDepAcademiccos;
    private javax.swing.JMenu menuPracticas;
    private javax.swing.JMenu menuProfesores;
    private javax.swing.JMenu menuTemas;
    // End of variables declaration//GEN-END:variables
}
